[FileDialog]
history=file:///home/sebastian/.config/picom, file:///home/sebastian, file:///home/sebastian/.config/polybar, file:///home/sebastian/.config/rofi, file:///home/sebastian/.config, file:///home/sebastian/.config/dunst
lastVisited=file:///home/sebastian/.config/dunst
qtVersion=5.15.7
shortcuts=file:, file:///home/sebastian
sidebarWidth=98
treeViewHeader=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xf8\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0r\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xda\0\0\0\x1\0\0\0\0\0\0\0L\0\0\0\x1\0\0\0\0\0\0\0L\0\0\0\x1\0\0\0\0\0\0\0\x86\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff)
viewMode=Detail
